/**
 * Path Utilities
 *
 * Functions for handling localized paths and URL generation.
 */

import type { Locale } from './types';
import { locales } from './locales';

/**
 * Blog path mapping - maps slug to localized slugs
 * Auto-generated by fix-canonical-slugs.mjs
 * Using Map for O(1) lookup performance
 */
const blogSlugTranslationsData: Record<string, Record<Locale, string>> = {
  'smas-anatomy-fundamentals': { en: 'smas-anatomy-fundamentals', 'pt': 'anatomia-smas-fundamentos', es: 'anatomia-smas-fundamentos' },
  'anatomia-smas-fundamentos': { en: 'smas-anatomy-fundamentals', 'pt': 'anatomia-smas-fundamentos', es: 'anatomia-smas-fundamentos' },
  'what-is-modern-face': { en: 'what-is-modern-face', 'pt': 'o-que-e-face-moderna', es: 'que-es-face-moderna' },
  'o-que-e-face-moderna': { en: 'what-is-modern-face', 'pt': 'o-que-e-face-moderna', es: 'que-es-face-moderna' },
  'que-es-face-moderna': { en: 'what-is-modern-face', 'pt': 'o-que-e-face-moderna', es: 'que-es-face-moderna' },
  'biostimulators-facial-surgery': { en: 'biostimulators-facial-surgery', 'pt': 'bioestimuladores-cirurgia-facial', es: 'bioestimuladores-cirugia-facial' },
  'bioestimuladores-cirurgia-facial': { en: 'biostimulators-facial-surgery', 'pt': 'bioestimuladores-cirurgia-facial', es: 'bioestimuladores-cirugia-facial' },
  'bioestimuladores-cirugia-facial': { en: 'biostimulators-facial-surgery', 'pt': 'bioestimuladores-cirurgia-facial', es: 'bioestimuladores-cirugia-facial' },
  'deep-neck-complete-guide': { en: 'deep-neck-complete-guide', 'pt': 'deep-neck-guia-completo', es: 'deep-neck-guia-completo' },
  'deep-neck-guia-completo': { en: 'deep-neck-complete-guide', 'pt': 'deep-neck-guia-completo', es: 'deep-neck-guia-completo' },
  'deep-neck-preserving-submandibular': { en: 'deep-neck-preserving-submandibular', 'pt': 'deep-neck-preservando-glandula-submandibular', es: 'deep-neck-preservando-glandula-submandibular' },
  'deep-neck-preservando-glandula-submandibular': { en: 'deep-neck-preserving-submandibular', 'pt': 'deep-neck-preservando-glandula-submandibular', es: 'deep-neck-preservando-glandula-submandibular' },
  'endomidface-complete-guide': { en: 'endomidface-complete-guide', 'pt': 'endomidface-guia-completo', es: 'endomidface-guia-completo' },
  'endomidface-guia-completo': { en: 'endomidface-complete-guide', 'pt': 'endomidface-guia-completo', es: 'endomidface-guia-completo' },
  'endomidface-direct-vision-technique': { en: 'endomidface-direct-vision-technique', 'pt': 'endomidface-por-visao-direta-tecnica', es: 'endomidface-por-vision-directa-tecnica' },
  'endomidface-por-visao-direta-tecnica': { en: 'endomidface-direct-vision-technique', 'pt': 'endomidface-por-visao-direta-tecnica', es: 'endomidface-por-vision-directa-tecnica' },
  'endomidface-por-vision-directa-tecnica': { en: 'endomidface-direct-vision-technique', 'pt': 'endomidface-por-visao-direta-tecnica', es: 'endomidface-por-vision-directa-tecnica' },
  'endomidface-vs-deep-plane': { en: 'endomidface-vs-deep-plane', 'pt': 'endomidface-vs-deep-plane', es: 'endomidface-vs-deep-plane' },
  'endomidface-ideal-candidates': { en: 'endomidface-ideal-candidates', 'pt': 'indicacoes-endomidface-casos-ideais', es: 'indicaciones-endomidface-casos-ideales' },
  'indicacoes-endomidface-casos-ideais': { en: 'endomidface-ideal-candidates', 'pt': 'indicacoes-endomidface-casos-ideais', es: 'indicaciones-endomidface-casos-ideales' },
  'indicaciones-endomidface-casos-ideales': { en: 'endomidface-ideal-candidates', 'pt': 'indicacoes-endomidface-casos-ideais', es: 'indicaciones-endomidface-casos-ideales' },
  'dr-roberio-brandao-creator-endomidface': { en: 'dr-roberio-brandao-creator-endomidface', 'pt': 'dr-roberio-brandao-criador-endomidface', es: 'dr-roberio-brandao-creador-endomidface' },
  'dr-roberio-brandao-criador-endomidface': { en: 'dr-roberio-brandao-creator-endomidface', 'pt': 'dr-roberio-brandao-criador-endomidface', es: 'dr-roberio-brandao-creador-endomidface' },
  'dr-roberio-brandao-creador-endomidface': { en: 'dr-roberio-brandao-creator-endomidface', 'pt': 'dr-roberio-brandao-criador-endomidface', es: 'dr-roberio-brandao-creador-endomidface' },
  'become-modern-face-surgeon': { en: 'become-modern-face-surgeon', 'pt': 'como-se-tornar-cirurgiao-face-moderna', es: 'convertirse-cirujano-face-moderna' },
  'como-se-tornar-cirurgiao-face-moderna': { en: 'become-modern-face-surgeon', 'pt': 'como-se-tornar-cirurgiao-face-moderna', es: 'convertirse-cirujano-face-moderna' },
  'convertirse-cirujano-face-moderna': { en: 'become-modern-face-surgeon', 'pt': 'como-se-tornar-cirurgiao-face-moderna', es: 'convertirse-cirujano-face-moderna' },
  'browlift-direct-vision-evolutionary-frontoplasty': { en: 'browlift-direct-vision-evolutionary-frontoplasty', 'pt': 'browlift-visao-direta-frontoplastia-evolutiva', es: 'browlift-vision-directa-frontoplastia' },
  'browlift-visao-direta-frontoplastia-evolutiva': { en: 'browlift-direct-vision-evolutionary-frontoplasty', 'pt': 'browlift-visao-direta-frontoplastia-evolutiva', es: 'browlift-vision-directa-frontoplastia' },
  'browlift-vision-directa-frontoplastia': { en: 'browlift-direct-vision-evolutionary-frontoplasty', 'pt': 'browlift-visao-direta-frontoplastia-evolutiva', es: 'browlift-vision-directa-frontoplastia' },
  'frontoplasty-browlift-complete-guide': { en: 'frontoplasty-browlift-complete-guide', 'pt': 'frontoplastia-browlift-guia-completo', es: 'frontoplastia-browlift-guia-completo' },
  'frontoplastia-browlift-guia-completo': { en: 'frontoplasty-browlift-complete-guide', 'pt': 'frontoplastia-browlift-guia-completo', es: 'frontoplastia-browlift-guia-completo' },
  'deep-plane-without-endoscope': { en: 'deep-plane-without-endoscope', 'pt': 'deep-plane-sem-endoscopio-alternativa', es: 'deep-plane-sin-endoscopio-alternativa' },
  'deep-plane-sem-endoscopio-alternativa': { en: 'deep-plane-without-endoscope', 'pt': 'deep-plane-sem-endoscopio-alternativa', es: 'deep-plane-sin-endoscopio-alternativa' },
  'deep-plane-sin-endoscopio-alternativa': { en: 'deep-plane-without-endoscope', 'pt': 'deep-plane-sem-endoscopio-alternativa', es: 'deep-plane-sin-endoscopio-alternativa' },
  'facelift-recovery-timeline': { en: 'facelift-recovery-timeline', 'pt': 'recuperacao-lifting-timeline', es: 'recuperacion-post-lifting-timeline' },
  'recuperacao-lifting-timeline': { en: 'facelift-recovery-timeline', 'pt': 'recuperacao-lifting-timeline', es: 'recuperacion-post-lifting-timeline' },
  'recuperacion-post-lifting-timeline': { en: 'facelift-recovery-timeline', 'pt': 'recuperacao-lifting-timeline', es: 'recuperacion-post-lifting-timeline' },
  'facelift-complications-prevention': { en: 'facelift-complications-prevention', 'pt': 'complicacoes-lifting-facial-prevencao', es: 'complicaciones-lifting-facial-prevencion' },
  'complicacoes-lifting-facial-prevencao': { en: 'facelift-complications-prevention', 'pt': 'complicacoes-lifting-facial-prevencao', es: 'complicaciones-lifting-facial-prevencion' },
  'complicaciones-lifting-facial-prevencion': { en: 'facelift-complications-prevention', 'pt': 'complicacoes-lifting-facial-prevencao', es: 'complicaciones-lifting-facial-prevencion' },
  'facelift-contraindications': { en: 'facelift-contraindications', 'pt': 'contraindicacoes-lifting-facial', es: 'contraindicaciones-lifting-facial' },
  'contraindicacoes-lifting-facial': { en: 'facelift-contraindications', 'pt': 'contraindicacoes-lifting-facial', es: 'contraindicaciones-lifting-facial' },
  'contraindicaciones-lifting-facial': { en: 'facelift-contraindications', 'pt': 'contraindicacoes-lifting-facial', es: 'contraindicaciones-lifting-facial' },
  'facelift-learning-curve': { en: 'facelift-learning-curve', 'pt': 'curva-aprendizado-lifting-facial', es: 'curva-aprendizaje-lifting-facial' },
  'curva-aprendizado-lifting-facial': { en: 'facelift-learning-curve', 'pt': 'curva-aprendizado-lifting-facial', es: 'curva-aprendizaje-lifting-facial' },
  'curva-aprendizaje-lifting-facial': { en: 'facelift-learning-curve', 'pt': 'curva-aprendizado-lifting-facial', es: 'curva-aprendizaje-lifting-facial' },
  'facelift-cost-benefit': { en: 'facelift-cost-benefit', 'pt': 'custo-beneficio-lifting-facial', es: 'costo-beneficio-lifting-facial' },
  'custo-beneficio-lifting-facial': { en: 'facelift-cost-benefit', 'pt': 'custo-beneficio-lifting-facial', es: 'costo-beneficio-lifting-facial' },
  'costo-beneficio-lifting-facial': { en: 'facelift-cost-benefit', 'pt': 'custo-beneficio-lifting-facial', es: 'costo-beneficio-lifting-facial' },
  'facelift-scar-care': { en: 'facelift-scar-care', 'pt': 'cicatriz-lifting-facial-cuidados', es: 'cicatriz-lifting-facial-cuidados' },
  'cicatriz-lifting-facial-cuidados': { en: 'facelift-scar-care', 'pt': 'cicatriz-lifting-facial-cuidados', es: 'cicatriz-lifting-facial-cuidados' },
  'facelift-at-40': { en: 'facelift-at-40', 'pt': 'lifting-facial-40-anos', es: 'lifting-facial-40-anos' },
  'lifting-facial-40-anos': { en: 'facelift-at-40', 'pt': 'lifting-facial-40-anos', es: 'lifting-facial-40-anos' },
  'facelift-at-60': { en: 'facelift-at-60', 'pt': 'lifting-facial-60-anos', es: 'lifting-facial-60-anos' },
  'lifting-facial-60-anos': { en: 'facelift-at-60', 'pt': 'lifting-facial-60-anos', es: 'lifting-facial-60-anos' },
  'facelift-after-weight-loss': { en: 'facelift-after-weight-loss', 'pt': 'lifting-facial-apos-perda-peso', es: 'lifting-facial-despues-perdida-peso' },
  'lifting-facial-apos-perda-peso': { en: 'facelift-after-weight-loss', 'pt': 'lifting-facial-apos-perda-peso', es: 'lifting-facial-despues-perdida-peso' },
  'lifting-facial-despues-perdida-peso': { en: 'facelift-after-weight-loss', 'pt': 'lifting-facial-apos-perda-peso', es: 'lifting-facial-despues-perdida-peso' },
  'facelift-smokers': { en: 'facelift-smokers', 'pt': 'lifting-facial-fumantes', es: 'lifting-facial-fumadores' },
  'lifting-facial-fumantes': { en: 'facelift-smokers', 'pt': 'lifting-facial-fumantes', es: 'lifting-facial-fumadores' },
  'lifting-facial-fumadores': { en: 'facelift-smokers', 'pt': 'lifting-facial-fumantes', es: 'lifting-facial-fumadores' },
  'facelift-diabetic-patients': { en: 'facelift-diabetic-patients', 'pt': 'lifting-facial-diabeticos', es: 'lifting-facial-diabeticos' },
  'lifting-facial-diabeticos': { en: 'facelift-diabetic-patients', 'pt': 'lifting-facial-diabeticos', es: 'lifting-facial-diabeticos' },
  'facelift-vs-fillers': { en: 'facelift-vs-fillers', 'pt': 'lifting-facial-vs-preenchedores', es: 'lifting-facial-vs-rellenos' },
  'lifting-facial-vs-preenchedores': { en: 'facelift-vs-fillers', 'pt': 'lifting-facial-vs-preenchedores', es: 'lifting-facial-vs-rellenos' },
  'lifting-facial-vs-rellenos': { en: 'facelift-vs-fillers', 'pt': 'lifting-facial-vs-preenchedores', es: 'lifting-facial-vs-rellenos' },
  'facelift-hematoma-prevention': { en: 'facelift-hematoma-prevention', 'pt': 'hematoma-lifting-facial-prevencao', es: 'hematoma-lifting-facial-prevencion' },
  'hematoma-lifting-facial-prevencao': { en: 'facelift-hematoma-prevention', 'pt': 'hematoma-lifting-facial-prevencao', es: 'hematoma-lifting-facial-prevencion' },
  'hematoma-lifting-facial-prevencion': { en: 'facelift-hematoma-prevention', 'pt': 'hematoma-lifting-facial-prevencao', es: 'hematoma-lifting-facial-prevencion' },
  'facelift-self-esteem-psychology': { en: 'facelift-self-esteem-psychology', 'pt': 'lifting-facial-autoestima-psicologia', es: 'lifting-facial-autoestima-psicologia' },
  'lifting-facial-autoestima-psicologia': { en: 'facelift-self-esteem-psychology', 'pt': 'lifting-facial-autoestima-psicologia', es: 'lifting-facial-autoestima-psicologia' },
  'facelift-myths-truths': { en: 'facelift-myths-truths', 'pt': 'mitos-lifting-facial-verdades', es: 'mitos-lifting-facial-verdades' },
  'mitos-lifting-facial-verdades': { en: 'facelift-myths-truths', 'pt': 'mitos-lifting-facial-verdades', es: 'mitos-lifting-facial-verdades' },
  'facelift-recovery-nutrition': { en: 'facelift-recovery-nutrition', 'pt': 'alimentacao-recuperacao-lifting', es: 'alimentacion-recuperacion-lifting' },
  'alimentacao-recuperacao-lifting': { en: 'facelift-recovery-nutrition', 'pt': 'alimentacao-recuperacao-lifting', es: 'alimentacion-recuperacion-lifting' },
  'alimentacion-recuperacion-lifting': { en: 'facelift-recovery-nutrition', 'pt': 'alimentacao-recuperacao-lifting', es: 'alimentacion-recuperacion-lifting' },
  'facelift-result-duration': { en: 'facelift-result-duration', 'pt': 'tempo-duracao-resultado-lifting', es: 'tiempo-duracion-resultado-lifting' },
  'tempo-duracao-resultado-lifting': { en: 'facelift-result-duration', 'pt': 'tempo-duracao-resultado-lifting', es: 'tiempo-duracion-resultado-lifting' },
  'tiempo-duracion-resultado-lifting': { en: 'facelift-result-duration', 'pt': 'tempo-duracao-resultado-lifting', es: 'tiempo-duracion-resultado-lifting' },
  'facelift-consultation-questions': { en: 'facelift-consultation-questions', 'pt': 'perguntas-consulta-lifting-facial', es: 'preguntas-consulta-lifting' },
  'perguntas-consulta-lifting-facial': { en: 'facelift-consultation-questions', 'pt': 'perguntas-consulta-lifting-facial', es: 'preguntas-consulta-lifting' },
  'preguntas-consulta-lifting': { en: 'facelift-consultation-questions', 'pt': 'perguntas-consulta-lifting-facial', es: 'preguntas-consulta-lifting' },
  'facelift-history-evolution': { en: 'facelift-history-evolution', 'pt': 'historia-lifting-facial-evolucao', es: 'historia-lifting-facial-evolucion' },
  'historia-lifting-facial-evolucao': { en: 'facelift-history-evolution', 'pt': 'historia-lifting-facial-evolucao', es: 'historia-lifting-facial-evolucion' },
  'historia-lifting-facial-evolucion': { en: 'facelift-history-evolution', 'pt': 'historia-lifting-facial-evolucao', es: 'historia-lifting-facial-evolucion' },
  'history-facial-surgery-evolution': { en: 'history-facial-surgery-evolution', 'pt': 'historia-cirurgia-facial-evolucao', es: 'historia-cirugia-facial-evolucion' },
  'historia-cirurgia-facial-evolucao': { en: 'history-facial-surgery-evolution', 'pt': 'historia-cirurgia-facial-evolucao', es: 'historia-cirugia-facial-evolucion' },
  'historia-cirugia-facial-evolucion': { en: 'history-facial-surgery-evolution', 'pt': 'historia-cirurgia-facial-evolucao', es: 'historia-cirugia-facial-evolucion' },
  'choosing-facelift-surgeon': { en: 'choosing-facelift-surgeon', 'pt': 'escolhendo-cirurgiao-lifting-facial', es: 'elegir-cirujano-lifting-facial' },
  'escolhendo-cirurgiao-lifting-facial': { en: 'choosing-facelift-surgeon', 'pt': 'escolhendo-cirurgiao-lifting-facial', es: 'elegir-cirujano-lifting-facial' },
  'elegir-cirujano-lifting-facial': { en: 'choosing-facelift-surgeon', 'pt': 'escolhendo-cirurgiao-lifting-facial', es: 'elegir-cirujano-lifting-facial' },
  'before-after-photos-importance': { en: 'before-after-photos-importance', 'pt': 'fotos-antes-depois-importancia', es: 'importancia-fotos-antes-despues' },
  'fotos-antes-depois-importancia': { en: 'before-after-photos-importance', 'pt': 'fotos-antes-depois-importancia', es: 'importancia-fotos-antes-despues' },
  'importancia-fotos-antes-despues': { en: 'before-after-photos-importance', 'pt': 'fotos-antes-depois-importancia', es: 'importancia-fotos-antes-despues' },
  'blepharoplasty-facelift-combined': { en: 'blepharoplasty-facelift-combined', 'pt': 'blefaroplastia-lifting-combinados', es: 'blefaroplastia-lifting-combinados' },
  'blefaroplastia-lifting-combinados': { en: 'blepharoplasty-facelift-combined', 'pt': 'blefaroplastia-lifting-combinados', es: 'blefaroplastia-lifting-combinados' },
  'cervicomental-angle-definition': { en: 'cervicomental-angle-definition', 'pt': 'angulo-cervicomental-definicao', es: 'angulo-cervicomental-definicion' },
  'angulo-cervicomental-definicao': { en: 'cervicomental-angle-definition', 'pt': 'angulo-cervicomental-definicao', es: 'angulo-cervicomental-definicion' },
  'angulo-cervicomental-definicion': { en: 'cervicomental-angle-definition', 'pt': 'angulo-cervicomental-definicao', es: 'angulo-cervicomental-definicion' },
  'platysmal-bands-correction': { en: 'platysmal-bands-correction', 'pt': 'bandas-platismais-correcao', es: 'bandas-platismales-correccion' },
  'bandas-platismais-correcao': { en: 'platysmal-bands-correction', 'pt': 'bandas-platismais-correcao', es: 'bandas-platismales-correccion' },
  'bandas-platismales-correccion': { en: 'platysmal-bands-correction', 'pt': 'bandas-platismais-correcao', es: 'bandas-platismales-correccion' },
  'facial-fat-aging-compartments': { en: 'facial-fat-aging-compartments', 'pt': 'gordura-facial-envelhecimento-compartimentos', es: 'grasa-facial-envejecimiento-compartimentos' },
  'gordura-facial-envelhecimento-compartimentos': { en: 'facial-fat-aging-compartments', 'pt': 'gordura-facial-envelhecimento-compartimentos', es: 'grasa-facial-envejecimiento-compartimentos' },
  'grasa-facial-envejecimiento-compartimentos': { en: 'facial-fat-aging-compartments', 'pt': 'gordura-facial-envelhecimento-compartimentos', es: 'grasa-facial-envejecimiento-compartimentos' },
  'facial-fat-aging': { en: 'facial-fat-aging', 'pt': 'gordura-facial-envelhecimento', es: 'grasa-facial-envejecimiento' },
  'gordura-facial-envelhecimento': { en: 'facial-fat-aging', 'pt': 'gordura-facial-envelhecimento', es: 'grasa-facial-envejecimiento' },
  'grasa-facial-envejecimiento': { en: 'facial-fat-aging', 'pt': 'gordura-facial-envelhecimento', es: 'grasa-facial-envejecimiento' },
  'deep-plane-facial-surgery': { en: 'deep-plane-facial-surgery', 'pt': 'plano-profundo-cirurgia-facial', es: 'plano-profundo-cirugia-facial' },
  'plano-profundo-cirurgia-facial': { en: 'deep-plane-facial-surgery', 'pt': 'plano-profundo-cirurgia-facial', es: 'plano-profundo-cirugia-facial' },
  'plano-profundo-cirugia-facial': { en: 'deep-plane-facial-surgery', 'pt': 'plano-profundo-cirurgia-facial', es: 'plano-profundo-cirugia-facial' },
  'facelift-injected-face-biostimulators': { en: 'facelift-injected-face-biostimulators', 'pt': 'lifting-face-injetada-bioestimuladores', es: 'lifting-rostro-inyectado-bioestimuladores' },
  'lifting-face-injetada-bioestimuladores': { en: 'facelift-injected-face-biostimulators', 'pt': 'lifting-face-injetada-bioestimuladores', es: 'lifting-rostro-inyectado-bioestimuladores' },
  'lifting-rostro-inyectado-bioestimuladores': { en: 'facelift-injected-face-biostimulators', 'pt': 'lifting-face-injetada-bioestimuladores', es: 'lifting-rostro-inyectado-bioestimuladores' },
  'facelift-without-expensive-equipment': { en: 'facelift-without-expensive-equipment', 'pt': 'lifting-sem-equipamento-caro', es: 'lifting-sin-equipamiento-caro' },
  'lifting-sem-equipamento-caro': { en: 'facelift-without-expensive-equipment', 'pt': 'lifting-sem-equipamento-caro', es: 'lifting-sin-equipamiento-caro' },
  'lifting-sin-equipamiento-caro': { en: 'facelift-without-expensive-equipment', 'pt': 'lifting-sem-equipamento-caro', es: 'lifting-sin-equipamiento-caro' },
  'facial-exercises-facelift-myth': { en: 'facial-exercises-facelift-myth', 'pt': 'exercicios-faciais-lifting-mito', es: 'ejercicios-faciales-lifting-mito' },
  'exercicios-faciais-lifting-mito': { en: 'facial-exercises-facelift-myth', 'pt': 'exercicios-faciais-lifting-mito', es: 'ejercicios-faciales-lifting-mito' },
  'ejercicios-faciales-lifting-mito': { en: 'facial-exercises-facelift-myth', 'pt': 'exercicios-faciais-lifting-mito', es: 'ejercicios-faciales-lifting-mito' },
  'numbness-sensitivity-post-facelift': { en: 'numbness-sensitivity-post-facelift', 'pt': 'dormencia-sensibilidade-pos-lifting', es: 'dormencia-sensibilidad-post-lifting' },
  'dormencia-sensibilidade-pos-lifting': { en: 'numbness-sensitivity-post-facelift', 'pt': 'dormencia-sensibilidade-pos-lifting', es: 'dormencia-sensibilidad-post-lifting' },
  'dormencia-sensibilidad-post-lifting': { en: 'numbness-sensitivity-post-facelift', 'pt': 'dormencia-sensibilidade-pos-lifting', es: 'dormencia-sensibilidad-post-lifting' },
  'massage-drainage-post-facelift': { en: 'massage-drainage-post-facelift', 'pt': 'massagem-facial-drenagem-pos-lifting', es: 'masaje-facial-drenaje-post-lifting' },
  'massagem-facial-drenagem-pos-lifting': { en: 'massage-drainage-post-facelift', 'pt': 'massagem-facial-drenagem-pos-lifting', es: 'masaje-facial-drenaje-post-lifting' },
  'masaje-facial-drenaje-post-lifting': { en: 'massage-drainage-post-facelift', 'pt': 'massagem-facial-drenagem-pos-lifting', es: 'masaje-facial-drenaje-post-lifting' },
  'mini-facelift-vs-full-facelift': { en: 'mini-facelift-vs-full-facelift', 'pt': 'mini-lifting-vs-lifting-completo', es: 'mini-lifting-vs-lifting-completo' },
  'mini-lifting-vs-lifting-completo': { en: 'mini-facelift-vs-full-facelift', 'pt': 'mini-lifting-vs-lifting-completo', es: 'mini-lifting-vs-lifting-completo' },
  'when-see-final-facelift-result': { en: 'when-see-final-facelift-result', 'pt': 'quando-ver-resultado-final-lifting', es: 'cuando-ver-resultado-final-lifting' },
  'quando-ver-resultado-final-lifting': { en: 'when-see-final-facelift-result', 'pt': 'quando-ver-resultado-final-lifting', es: 'cuando-ver-resultado-final-lifting' },
  'cuando-ver-resultado-final-lifting': { en: 'when-see-final-facelift-result', 'pt': 'quando-ver-resultado-final-lifting', es: 'cuando-ver-resultado-final-lifting' },
  'skincare-post-facelift': { en: 'skincare-post-facelift', 'pt': 'skincare-pos-lifting', es: 'skincare-post-lifting' },
  'skincare-pos-lifting': { en: 'skincare-post-facelift', 'pt': 'skincare-pos-lifting', es: 'skincare-post-lifting' },
  'skincare-post-lifting': { en: 'skincare-post-facelift', 'pt': 'skincare-pos-lifting', es: 'skincare-post-lifting' },
  'facial-surgery-trends-2025': { en: 'facial-surgery-trends-2025', 'pt': 'tendencias-cirurgia-facial-2025', es: 'tendencias-cirugia-facial-2025' },
  'tendencias-cirurgia-facial-2025': { en: 'facial-surgery-trends-2025', 'pt': 'tendencias-cirurgia-facial-2025', es: 'tendencias-cirugia-facial-2025' },
  'tendencias-cirugia-facial-2025': { en: 'facial-surgery-trends-2025', 'pt': 'tendencias-cirurgia-facial-2025', es: 'tendencias-cirugia-facial-2025' },
  'microfocused-ultrasound-vs-facelift': { en: 'microfocused-ultrasound-vs-facelift', 'pt': 'ultrassom-microfocado-vs-lifting', es: 'ultrasonido-microfocalizado-vs-lifting' },
  'ultrassom-microfocado-vs-lifting': { en: 'microfocused-ultrasound-vs-facelift', 'pt': 'ultrassom-microfocado-vs-lifting', es: 'ultrasonido-microfocalizado-vs-lifting' },
  'ultrasonido-microfocalizado-vs-lifting': { en: 'microfocused-ultrasound-vs-facelift', 'pt': 'ultrassom-microfocado-vs-lifting', es: 'ultrasonido-microfocalizado-vs-lifting' },
  'vertical-vs-lateral-vector-facelift': { en: 'vertical-vs-lateral-vector-facelift', 'pt': 'vetor-vertical-vs-lateral-lifting', es: 'vector-vertical-vs-lateral-lifting' },
  'vetor-vertical-vs-lateral-lifting': { en: 'vertical-vs-lateral-vector-facelift', 'pt': 'vetor-vertical-vs-lateral-lifting', es: 'vector-vertical-vs-lateral-lifting' },
  'vector-vertical-vs-lateral-lifting': { en: 'vertical-vs-lateral-vector-facelift', 'pt': 'vetor-vertical-vs-lateral-lifting', es: 'vector-vertical-vs-lateral-lifting' },
  'modern-face-concept-philosophy': { en: 'modern-face-concept-philosophy', 'pt': 'face-moderna-conceito-filosofia', es: 'face-moderna-concepto-filosofia' },
  'face-moderna-conceito-filosofia': { en: 'modern-face-concept-philosophy', 'pt': 'face-moderna-conceito-filosofia', es: 'face-moderna-concepto-filosofia' },
  'face-moderna-concepto-filosofia': { en: 'modern-face-concept-philosophy', 'pt': 'face-moderna-conceito-filosofia', es: 'face-moderna-concepto-filosofia' },
  'modern-face-institute-about': { en: 'modern-face-institute-about', 'pt': 'instituto-face-moderna-sobre', es: 'instituto-face-moderna-sobre' },
  'instituto-face-moderna-sobre': { en: 'modern-face-institute-about', 'pt': 'instituto-face-moderna-sobre', es: 'instituto-face-moderna-sobre' },
  'patient-selection-facial-surgery': { en: 'patient-selection-facial-surgery', 'pt': 'selecao-pacientes-cirurgia-facial', es: 'seleccion-pacientes-cirugia-facial' },
  'selecao-pacientes-cirurgia-facial': { en: 'patient-selection-facial-surgery', 'pt': 'selecao-pacientes-cirurgia-facial', es: 'seleccion-pacientes-cirugia-facial' },
  'seleccion-pacientes-cirugia-facial': { en: 'patient-selection-facial-surgery', 'pt': 'selecao-pacientes-cirurgia-facial', es: 'seleccion-pacientes-cirugia-facial' },
  'complete-facial-surgery-planning': { en: 'complete-facial-surgery-planning', 'pt': 'planejamento-cirurgico-facial-completo', es: 'planificacion-quirurgica-facial-completa' },
  'planejamento-cirurgico-facial-completo': { en: 'complete-facial-surgery-planning', 'pt': 'planejamento-cirurgico-facial-completo', es: 'planificacion-quirurgica-facial-completa' },
  'planificacion-quirurgica-facial-completa': { en: 'complete-facial-surgery-planning', 'pt': 'planejamento-cirurgico-facial-completo', es: 'planificacion-quirurgica-facial-completa' },
  'preoperative-facelift-planning': { en: 'preoperative-facelift-planning', 'pt': 'planejamento-pre-operatorio-lifting', es: 'planificacion-preoperatoria-lifting' },
  'planejamento-pre-operatorio-lifting': { en: 'preoperative-facelift-planning', 'pt': 'planejamento-pre-operatorio-lifting', es: 'planificacion-preoperatoria-lifting' },
  'planificacion-preoperatoria-lifting': { en: 'preoperative-facelift-planning', 'pt': 'planejamento-pre-operatorio-lifting', es: 'planificacion-preoperatoria-lifting' },
  'local-anesthesia-facial-surgery': { en: 'local-anesthesia-facial-surgery', 'pt': 'anestesia-local-cirurgia-facial', es: 'anestesia-local-cirugia-facial' },
  'anestesia-local-cirurgia-facial': { en: 'local-anesthesia-facial-surgery', 'pt': 'anestesia-local-cirurgia-facial', es: 'anestesia-local-cirugia-facial' },
  'anestesia-local-cirugia-facial': { en: 'local-anesthesia-facial-surgery', 'pt': 'anestesia-local-cirurgia-facial', es: 'anestesia-local-cirugia-facial' },
  'technology-facial-surgery-modern': { en: 'technology-facial-surgery-modern', 'pt': 'tecnologia-cirurgia-facial-moderna', es: 'tecnologia-cirugia-facial-moderna' },
  'tecnologia-cirurgia-facial-moderna': { en: 'technology-facial-surgery-modern', 'pt': 'tecnologia-cirurgia-facial-moderna', es: 'tecnologia-cirugia-facial-moderna' },
  'tecnologia-cirugia-facial-moderna': { en: 'technology-facial-surgery-modern', 'pt': 'tecnologia-cirurgia-facial-moderna', es: 'tecnologia-cirugia-facial-moderna' },
  'natural-results-facelift': { en: 'natural-results-facelift', 'pt': 'resultados-naturais-lifting-facial', es: 'resultados-naturales-lifting-facial' },
  'resultados-naturais-lifting-facial': { en: 'natural-results-facelift', 'pt': 'resultados-naturais-lifting-facial', es: 'resultados-naturales-lifting-facial' },
  'resultados-naturales-lifting-facial': { en: 'natural-results-facelift', 'pt': 'resultados-naturais-lifting-facial', es: 'resultados-naturales-lifting-facial' },
  'facelift-male-differences': { en: 'facelift-male-differences', 'pt': 'lifting-facial-masculino-diferencas', es: 'lifting-facial-masculino-diferencias' },
  'lifting-facial-masculino-diferencas': { en: 'facelift-male-differences', 'pt': 'lifting-facial-masculino-diferencas', es: 'lifting-facial-masculino-diferencias' },
  'lifting-facial-masculino-diferencias': { en: 'facelift-male-differences', 'pt': 'lifting-facial-masculino-diferencas', es: 'lifting-facial-masculino-diferencias' },
  'second-facelift-revision': { en: 'second-facelift-revision', 'pt': 'lifting-facial-segunda-vez-revisao', es: 'lifting-facial-segunda-vez-revision' },
  'lifting-facial-segunda-vez-revisao': { en: 'second-facelift-revision', 'pt': 'lifting-facial-segunda-vez-revisao', es: 'lifting-facial-segunda-vez-revision' },
  'lifting-facial-segunda-vez-revision': { en: 'second-facelift-revision', 'pt': 'lifting-facial-segunda-vez-revisao', es: 'lifting-facial-segunda-vez-revision' },
  'first-facelift-50-years': { en: 'first-facelift-50-years', 'pt': 'primeiro-lifting-50-anos-guia', es: 'primer-lifting-50-anos-guia' },
  'primeiro-lifting-50-anos-guia': { en: 'first-facelift-50-years', 'pt': 'primeiro-lifting-50-anos-guia', es: 'primer-lifting-50-anos-guia' },
  'primer-lifting-50-anos-guia': { en: 'first-facelift-50-years', 'pt': 'primeiro-lifting-50-anos-guia', es: 'primer-lifting-50-anos-guia' },
  'lymphatic-drainage-post-facelift': { en: 'lymphatic-drainage-post-facelift', 'pt': 'drenagem-linfatica-pos-lifting-facial', es: 'drenaje-linfatico-post-lifting-facial' },
  'drenagem-linfatica-pos-lifting-facial': { en: 'lymphatic-drainage-post-facelift', 'pt': 'drenagem-linfatica-pos-lifting-facial', es: 'drenaje-linfatico-post-lifting-facial' },
  'drenaje-linfatico-post-lifting-facial': { en: 'lymphatic-drainage-post-facelift', 'pt': 'drenagem-linfatica-pos-lifting-facial', es: 'drenaje-linfatico-post-lifting-facial' },
  'edema-swelling-post-facelift-evolution': { en: 'edema-swelling-post-facelift-evolution', 'pt': 'edema-inchaco-pos-lifting-evolucao', es: 'edema-hinchazon-post-lifting-evolucion' },
  'edema-inchaco-pos-lifting-evolucao': { en: 'edema-swelling-post-facelift-evolution', 'pt': 'edema-inchaco-pos-lifting-evolucao', es: 'edema-hinchazon-post-lifting-evolucion' },
  'edema-hinchazon-post-lifting-evolucion': { en: 'edema-swelling-post-facelift-evolution', 'pt': 'edema-inchaco-pos-lifting-evolucao', es: 'edema-hinchazon-post-lifting-evolucion' },
  'facial-retaining-ligaments': { en: 'facial-retaining-ligaments', 'pt': 'ligamentos-retentores-faciais', es: 'ligamentos-retentores-faciales' },
  'ligamentos-retentores-faciais': { en: 'facial-retaining-ligaments', 'pt': 'ligamentos-retentores-faciais', es: 'ligamentos-retentores-faciales' },
  'ligamentos-retentores-faciales': { en: 'facial-retaining-ligaments', 'pt': 'ligamentos-retentores-faciais', es: 'ligamentos-retentores-faciales' },
  'facial-nerve-surgery-protection': { en: 'facial-nerve-surgery-protection', 'pt': 'nervo-facial-cirurgia-protecao', es: 'nervio-facial-cirugia-proteccion' },
  'nervo-facial-cirurgia-protecao': { en: 'facial-nerve-surgery-protection', 'pt': 'nervo-facial-cirurgia-protecao', es: 'nervio-facial-cirugia-proteccion' },
  'nervio-facial-cirugia-proteccion': { en: 'facial-nerve-surgery-protection', 'pt': 'nervo-facial-cirurgia-protecao', es: 'nervio-facial-cirugia-proteccion' },
  'prezygomatic-space-anatomy': { en: 'prezygomatic-space-anatomy', 'pt': 'espaco-pre-zigomatico-anatomia', es: 'espacio-pre-zigomatico-anatomia' },
  'espaco-pre-zigomatico-anatomia': { en: 'prezygomatic-space-anatomy', 'pt': 'espaco-pre-zigomatico-anatomia', es: 'espacio-pre-zigomatico-anatomia' },
  'espacio-pre-zigomatico-anatomia': { en: 'prezygomatic-space-anatomy', 'pt': 'espaco-pre-zigomatico-anatomia', es: 'espacio-pre-zigomatico-anatomia' },
  'jowls-treatment': { en: 'jowls-treatment', 'pt': 'tratamento-jowls-papada', es: 'tratamiento-jowls-papada' },
  'tratamento-jowls-papada': { en: 'jowls-treatment', 'pt': 'tratamento-jowls-papada', es: 'tratamiento-jowls-papada' },
  'tratamiento-jowls-papada': { en: 'jowls-treatment', 'pt': 'tratamento-jowls-papada', es: 'tratamiento-jowls-papada' },
  'malar-ptosis-treatment': { en: 'malar-ptosis-treatment', 'pt': 'tratamento-ptose-malar', es: 'tratamiento-ptosis-malar' },
  'tratamento-ptose-malar': { en: 'malar-ptosis-treatment', 'pt': 'tratamento-ptose-malar', es: 'tratamiento-ptosis-malar' },
  'tratamiento-ptosis-malar': { en: 'malar-ptosis-treatment', 'pt': 'tratamento-ptose-malar', es: 'tratamiento-ptosis-malar' },
  'nasolabial-fold-correction': { en: 'nasolabial-fold-correction', 'pt': 'correcao-sulco-nasogeniano', es: 'correccion-surco-nasogeniano' },
  'correcao-sulco-nasogeniano': { en: 'nasolabial-fold-correction', 'pt': 'correcao-sulco-nasogeniano', es: 'correccion-surco-nasogeniano' },
  'correccion-surco-nasogeniano': { en: 'nasolabial-fold-correction', 'pt': 'correcao-sulco-nasogeniano', es: 'correccion-surco-nasogeniano' },
  'smas-what-is-importance': { en: 'smas-what-is-importance', 'pt': 'smas-o-que-e-importancia', es: 'smas-que-es-importancia' },
  'smas-o-que-e-importancia': { en: 'smas-what-is-importance', 'pt': 'smas-o-que-e-importancia', es: 'smas-que-es-importancia' },
  'smas-que-es-importancia': { en: 'smas-what-is-importance', 'pt': 'smas-o-que-e-importancia', es: 'smas-que-es-importancia' },
  'fat-grafting-facelift': { en: 'fat-grafting-facelift', 'pt': 'fat-grafting-lifting-facial', es: 'fat-grafting-lifting-facial' },
  'fat-grafting-lifting-facial': { en: 'fat-grafting-facelift', 'pt': 'fat-grafting-lifting-facial', es: 'fat-grafting-lifting-facial' },
  'pdo-threads-vs-surgical-facelift': { en: 'pdo-threads-vs-surgical-facelift', 'pt': 'fios-pdo-vs-lifting-cirurgico', es: 'hilos-pdo-vs-lifting-quirurgico' },
  'fios-pdo-vs-lifting-cirurgico': { en: 'pdo-threads-vs-surgical-facelift', 'pt': 'fios-pdo-vs-lifting-cirurgico', es: 'hilos-pdo-vs-lifting-quirurgico' },
  'hilos-pdo-vs-lifting-quirurgico': { en: 'pdo-threads-vs-surgical-facelift', 'pt': 'fios-pdo-vs-lifting-cirurgico', es: 'hilos-pdo-vs-lifting-quirurgico' },
};

// Convert to Map for O(1) lookups
const blogSlugTranslations = new Map<string, Record<Locale, string>>(
  Object.entries(blogSlugTranslationsData)
);

// Cache for memoizing translatePath results
const translatePathCache = new Map<string, string>();

/**
 * Get the current locale from the URL
 */
export function getLocaleFromUrl(url: URL): Locale {
  const pathname = url.pathname;
  const segments = pathname.split('/').filter(Boolean);

  if (segments[0] === 'pt') return 'pt';
  if (segments[0] === 'es') return 'es';
  return 'en';
}

/**
 * Get the locale prefix for URLs
 */
export function getLocalePrefix(locale: Locale): string {
  if (locale === 'en') return '';
  if (locale === 'pt') return '/pt';
  return `/${locale}`;
}

/**
 * Generate a localized path
 * @param path - The path without locale prefix (e.g., '/about')
 * @param locale - Target locale
 */
export function localizedPath(path: string, locale: Locale): string {
  // Remove any existing locale prefix
  let cleanPath = path.replace(/^\/(pt|es)\//, '/').replace(/^\/(pt|es)$/, '/');

  // Ensure path starts with /
  if (!cleanPath.startsWith('/')) {
    cleanPath = '/' + cleanPath;
  }

  // Handle root path
  if (cleanPath === '/') {
    return locale === 'en' ? '/' : getLocalePrefix(locale);
  }

  // Add locale prefix for non-default locales
  if (locale === 'en') {
    return cleanPath;
  }

  return `${getLocalePrefix(locale)}${cleanPath}`;
}

/**
 * Remove locale prefix from a path
 */
export function removeLocaleFromPath(path: string): string {
  return path.replace(/^\/(pt|es)\//, '/').replace(/^\/(pt|es)$/, '/');
}

/**
 * Map canonical Face Moderna® paths across locales
 */
const pathTranslationByKey: Record<string, Record<Locale, string>> = {
  'face-moderna-root': {
    en: '/modern-face',
    'pt': '/pt/face-moderna',
    es: '/es/face-moderna',
  },
  'face-moderna-what-is': {
    en: '/modern-face/what-is-it',
    'pt': '/pt/face-moderna/o-que-e',
    es: '/es/face-moderna/que-es',
  },
  'face-moderna-philosophy': {
    en: '/modern-face/philosophy',
    'pt': '/pt/face-moderna/filosofia',
    es: '/es/face-moderna/filosofia',
  },
  'face-moderna-principles': {
    en: '/modern-face/principles',
    'pt': '/pt/face-moderna/principios',
    es: '/es/face-moderna/principios',
  },
  'face-moderna-why-direct-vision': {
    en: '/modern-face/why-direct-vision',
    'pt': '/pt/face-moderna/por-que-visao-direta',
    es: '/es/face-moderna/por-que-vision-directa',
  },
  'face-moderna-evolution': {
    en: '/modern-face/evolution-of-facial-surgery',
    'pt': '/pt/face-moderna/evolucao-da-cirurgia-facial',
    es: '/es/face-moderna/evolucion-de-la-cirugia-facial',
  },
  'face-moderna-knowledge-sharing': {
    en: '/modern-face/knowledge-sharing',
    'pt': '/pt/face-moderna/socializacao-do-conhecimento',
    es: '/es/face-moderna/socializacion-del-conocimiento',
  },
  'techniques-new-technique': {
    en: '/techniques/new-technique',
    'pt': '/pt/tecnicas/nova-tecnica',
    es: '/es/tecnicas/nueva-tecnica',
  },
};

// Lookup to resolve the canonical key from a localized path (locale prefix already removed)
// Using Maps for O(1) lookup performance
const pathKeyByLocalePathData: Record<Locale, Record<string, string>> = {
  en: {
    '/modern-face': 'face-moderna-root',
    '/modern-face/what-is-it': 'face-moderna-what-is',
    '/modern-face/philosophy': 'face-moderna-philosophy',
    '/modern-face/principles': 'face-moderna-principles',
    '/modern-face/why-direct-vision': 'face-moderna-why-direct-vision',
    '/modern-face/evolution-of-facial-surgery': 'face-moderna-evolution',
    '/modern-face/knowledge-sharing': 'face-moderna-knowledge-sharing',
    '/techniques/new-technique': 'techniques-new-technique',
  },
  'pt': {
    '/face-moderna': 'face-moderna-root',
    '/face-moderna/o-que-e': 'face-moderna-what-is',
    '/face-moderna/filosofia': 'face-moderna-philosophy',
    '/face-moderna/principios': 'face-moderna-principles',
    '/face-moderna/por-que-visao-direta': 'face-moderna-why-direct-vision',
    '/face-moderna/evolucao-da-cirurgia-facial': 'face-moderna-evolution',
    '/face-moderna/socializacao-do-conhecimento': 'face-moderna-knowledge-sharing',
    '/tecnicas/nova-tecnica': 'techniques-new-technique',
  },
  es: {
    '/face-moderna': 'face-moderna-root',
    '/face-moderna/que-es': 'face-moderna-what-is',
    '/face-moderna/filosofia': 'face-moderna-philosophy',
    '/face-moderna/principios': 'face-moderna-principles',
    '/face-moderna/por-que-vision-directa': 'face-moderna-why-direct-vision',
    '/face-moderna/evolucion-de-la-cirugia-facial': 'face-moderna-evolution',
    '/face-moderna/socializacion-del-conocimiento': 'face-moderna-knowledge-sharing',
    '/tecnicas/nueva-tecnica': 'techniques-new-technique',
  },
};

// Convert to Maps for O(1) lookups
const pathKeyByLocalePath = new Map<Locale, Map<string, string>>();
for (const [locale, paths] of Object.entries(pathKeyByLocalePathData) as [Locale, Record<string, string>][]) {
  pathKeyByLocalePath.set(locale, new Map(Object.entries(paths)));
}

function normalizePath(path: string): string {
  const withoutLocale = removeLocaleFromPath(path);
  const trimmed = withoutLocale.replace(/\/+$/, '');
  return trimmed === '' ? '/' : trimmed;
}

/**
 * Check if a path is a blog post path and extract the slug
 */
function extractBlogSlug(path: string): string | null {
  // Match /blog/slug, /pt/blog/slug, /es/blog/slug
  const match = path.match(/^(?:\/(?:pt|es))?\/blog\/([^/]+)\/?$/);
  return match ? match[1] : null;
}

/**
 * Translate a path to the target locale, preserving known slugs
 * Falls back to simple prefixing when no mapping exists.
 * 
 * For blog posts: if no translation mapping exists, redirects to blog index
 * to avoid 404 errors when switching languages.
 * 
 * Results are memoized for performance.
 */
export function translatePath(path: string, locale: Locale): string {
  // Check cache first (O(1) lookup)
  const cacheKey = `${path}::${locale}`;
  const cached = translatePathCache.get(cacheKey);
  if (cached !== undefined) {
    return cached;
  }

  const cleanPath = normalizePath(path);

  // Special handling for blog posts
  const blogSlug = extractBlogSlug(cleanPath);
  if (blogSlug) {
    // Check if we have a translation mapping for this blog post (O(1) lookup with Map)
    const translatedSlug = blogSlugTranslations.get(blogSlug)?.[locale];
    const result = translatedSlug
      ? `${getLocalePrefix(locale)}/blog/${translatedSlug}`
      : `${getLocalePrefix(locale)}/blog`;
    
    translatePathCache.set(cacheKey, result);
    return result;
  }

  // Try to find canonical key from all locale maps (O(1) per locale)
  let key: string | undefined;
  for (const [, pathMap] of pathKeyByLocalePath.entries()) {
    key = pathMap.get(cleanPath);
    if (key) break;
  }

  const result = (key && pathTranslationByKey[key]?.[locale])
    ? pathTranslationByKey[key][locale]
    : localizedPath(cleanPath, locale);

  translatePathCache.set(cacheKey, result);
  return result;
}

/**
 * Get all alternate URLs for hreflang tags
 */
export function getAlternateUrls(
  currentPath: string,
  siteUrl: string
): { locale: Locale; url: string; hreflang: string }[] {
  return locales.map((locale) => ({
    locale,
    url: `${siteUrl}${translatePath(currentPath, locale)}`,
    hreflang: locale === 'pt' ? 'pt-BR' : locale,
  }));
}
